name: Simulations

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: install prerequisites
      run: |
        python -m pip install --upgrade pip
        pip install loguru
        pip install pycparser
    - name: string test
      if: always()
    - name: float test
      run: |
        cd SoC/Test
        make clean
        make all
        make test
      run: |
        cd libc/string
        make clean
        make all
        make test
    - name: stdlib test
      run: |
        cd libc/stdlib
        make clean
        make all
        make test
