name: Simulations

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: make all
      run: |
        cd libc/string
        make all
    - name: make test
      run: |
        cd libc/string
        make test
